### ISSUE TITLE
Peer Review Links

### ISSUE THREAD

**Issue by Xuis** [TaylorJesse/CSCI3308CollegeCrusaders#1]
Hey, would you please get me the links to your peer-review videos? You have them here as an screenshot of a URL, and I'd really appreciate not having to type each one out.
Thanks!

**Comment by TaylorJesse** [comment]
Hello! I'm sorry about that, I believe it's because we uploaded it as a PDF, if you go to the top right corner and click download, the downloaded PDF should have clickable links. Let me know if that doesn't work!

**Comment by Xuis** [comment]
That did work, thanks a bunch!
